# -*- coding: utf-8 -*-
"""CrudcomPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nfj2q50qnT90ZGnIBi_THR4AZwQvRz0-
"""

# Commented out IPython magic to ensure Python compatibility.
# ETE PD 
# PNT1
# PROF. CLOVES
# Crud com Python

# PRIMEIRA PARTE
class Matricula:
  def __init__(self):
    self.nome = input('Digite nome do aluno: ')
    self.datanascimento = input('Digite sua data de nascimento: ')
    self.numero = input('Digite o número da matrícula: ')
    self.cidade = input('Digite qual a sua cidade: ')

  def aluno(self, nome, datanascimento, numero, cidade):
    self = Matricula ()
    self.nome = ' ' 
    self.datanascimento = ' '
    self.numero = ' '
    self.cidade = ' '
    return self

# SEGUNDA PARTE
class Matricula:
  def __init__(self):
    self.nome = input('Digite nome do aluno: ')
    self.datanascimento = input('Digite sua data de nascimento: ')
    self.numero = input('Digite o número da matrícula: ')
    self.cidade = input('Digite qual a sua cidade: ')

  def aluno(self, nome, senha):
    self = Matricula()
    self.nome = input('Digite nome do aluno: ')
    self.datanascimento = input('Digite sua data de nascimento: ')
    self.numero = input('Digite o número da matrícula: ')
    self.cidade = input('Digite qual a sua cidade: ')
    return 
    
# TERCEIRA PARTE
opc = int(input('Cadastrar, digite 1\nConsultar, digite 2 \nOpção: '))
print()
if opc == 1:
    banco = (NovaMatricula())
    lista.append(banco)
    print('Cadastrado com sucesso! \nID: %i \nCliente: %s \nConta: %i '
#           %(banco.ID, banco.Matricula, banco.conta))
    print('-'*25)
elif opc == 2:

    consulta = int(input('Digite o ID: '))
    if consulta not in lista:
        print('Não contém')
    else:
        print(consulta[lista])**

# PARTE FINAL  
class usuario:
    ID = 0
    matricula = ' '
    conta = 0


  def NovaConta():
    nc = usuario() 
    nc.ID = int(input('Digite um ID): '))
    nc.cliente = input('Digite Nome: ')
    nc.conta = int(input('Digite número da conta: '))
    print()
    return nc