# -*- coding: utf-8 -*-
"""verificacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iYgLmi8zPVzGyAQT-m9h2nsclf7rbB0p
"""



print('Olá ETE Porto Digital')

numero = input('Digite um número: ')
print(f'O número informado foi: {numero}')

print('Calcule o raio e a área de um círculo com 50m de diâmetro')
diâmetro = 50
print('O diâmetro desse raio é: ' , (diâmetro/2))
print('E sua área é:' , (3.142*25**2))

prof = float (input('Informe o primeiro número:' ))
cloves = float (input('Informe o segundo número:' ))
soma = prof + cloves
print(soma)

a=input(‘digite:M ou F para informar seu sexo,sendo M-masculino e F-feminino:’)
                       if a==’F’
                       print(‘feminino’)
                       else: 
                       if a== ‘M’
                       print(‘M - Masculino, Sexo Inválido’)
                       else: 
                       print(‘Letra não correspondida’)

num = float(input('Digite um valor: '))
print('O número informado foi:', num)

num1 = int(input('Digite um número: '))
num2 = int(input('Digite outro número: '))
soma = num1 + num2
print("O valor da soma é:", soma)

nota1 = float(input("Digite sua primeira nota: "))
nota2 = float(input("Digite sua segunda nota: "))
nota3 = float(input("Digite sua terceira nota: "))
nota4 = float(input("Digite sua quarta nota: "))
media = (nota1 + nota2 + nota3 + nota4)/4
print("Sua média é: ", media)

m = float(input("Digite os mestros a serem convertidos: "))
cm = m*100
print("Centimetros: ", cm)

pi = 3.14
r = float(input('Digite o raio: '))
a = pi*(r*r)
print('A área do circulo é:', a)

altura = float(input('Digite a altura do quadrado: '))
base = float(input('Digite a base do quadrado: '))
result = base * altura
print('Área do quadrado: ', result)

x = 10.5
print(x)

x = 9
y = 9
print(x == y)

y = 10 
x = 9 
print(y * x)

c = 560
print(,'O número digitado foi: {c}')

altura = float(input('Digite a altura do quadrado: '))
base = float(input('Digite a base do quadrado: '))
result = base * altura
print('Área do quadrado: ', result)
AreaAoQuadrado = result * 2
print('Dobro da área do quadrado: ', AreaAoQuadrado)

if sex == 'M':
  print('Masculino')
elif sex == 'F' :
  print('Feminino')
else:
  print('Sexo Inválido')

A = NUMERO = float (input('informe a primeira nota '))
B = NUMERO = int (input('informe a segunda nota  '))
C = NUMERO = int (input('informe a terceira nota '))
D = NUMERO = int (input('informe a quarta nota '))
MEDIAFINAL = ((A + B + C + D ) / 4)
print('media final é', MEDIAFINAL)

raio = int (input('Diga o valor do raio do círculo: '))
π = 3.14 
área = π * raio**2
print('A área do círculo é:', área)

numero=input("Digite o número desejado: ")
		#Digite o número desejado: 1
print("O número informado foi ", numero)
		#O número informado foi  1

resposta = input('M ou F: ')

  if resposta == 'M':
		      print('Masculina')
  else:
if resposta == 'F':
      print('Feminina')
else:
              print('Você não digitou M ou F')

pi = 3.14
raio = 2 
area = pi * (r*r) 
print ('A área do círculo é:', area)

print("informe suas quatro notas bimestrais para obter sua media:")
nota1= float(input("média do primeiro bimestre:"))
nota2= float(input("média do segundo bimestre:"))
nota3= float(input("média do terceiro bimestre:"))
nota4= float(input("média do quarto bimestre:"))
mf=(nota1+nota2+nota3+nota4)/4
print("a sua media final é igual a:",mf)

metros = float (input('Digite a quantidade de metros: '))
x = metros * 100
#se
if metros < 0: 
print('Não é possível realizar metros negativos.')

elif metros == 0:
print(f'{metros} xé igual a {} centímetro.')

#senao
else:
print(f'O número {metros} é tantos metros:')

nota1 = float(input("Insira a sua primeira nota: "))
nota2 = float(input("Insira a sua segunda nota: "))
nota3 = float(input("Insira a sua terceira nota: "))
nota4 = float(input("Insira a sua quarta nota: "))
somanotas = nota1 + nota2 + nota3 + nota4
media = somanotas / 4
media2 = "%.2f" % media
print(f"Sua média bimestral é {media2}.")



nome = input('Digite seu nome: ')
print(f'Seu nome é {nome}.')

n1 = float(input('Qual foi a sua nota 1?' ))
n2 = float(input('Qual foi a sua nota 2?'))
n3 = float(input('Qual foi a sua nota 3?'))
n4 = float(input('Qual foi a sua nota 4?'))
print('A sua média final foi:' , (n1 + n2 + n3 + n4) /4)

n1 = float(input("Digite um número: "))
n2 = float(input("Digite outro número: "))
nr = n1+n2
print ("A soma entre {} e {} resulta em {}".format(n1,n2,nr))

n1 = float(input("Digite sua primeira nota: "))
n2 = float(input("Digite sua segunda nota: "))
n3 = float(input("Digite sua terceira nota: "))
n4 = float(input("Digite sua quarta nota: "))
mf = (n1+n2+n3+n4)/4
print("sua média final será {}".format(mf))

x = float (input("Digite um número: "))
#se 
if x > 0:
  print (f'O número {x} é positivo.')
elif x == 0:
  print ('O número é neutro.')
#e o senao 
else:
  print (f'O número {x} é negativo')

"print('Olá ETE PORTO DIGITAL!')"
      ],
      "execution_count": 25,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Olá ETE PORTO DIGITAL!\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "kOdeipdMTq7E",
        "outputId": "3f6c383c-ff02-475c-b838-f0f98583c986"
      },
      "source": [
        "# at2\n",
        " \n",
        "n = input('Digite um numero :')\n",
        "print('O numero que você digitou foi :', n , '.')"
      ],
      "execution_count": 27,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "digite um numero :8\n",
            "o numero que você digitou foi : 8 .\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "4Gjy-51inEZZ",
        "outputId": "7b382403-a4ad-4303-f682-6461ec2878bc"
      },
      "source": [
        "# at3\n",
        "\n",
        "man = int(input('Digite um numero '))\n",
        "no = int(input('Digite um segundo numero '))\n",
        "print('A soma desses números é', man + no, '.')"
      ],
      "execution_count": 98,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Digite um numero 25\n",
            "Digite um segundo numero 68\n",
            "A soma desses números é 93 .\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 248
        },
        "id": "U2v-iNlcMHy6",
        "outputId": "80bf48e5-9a5e-4234-ade5-3446701b07f5"
      },
      "source": [
        "# at4\n",
        " \n",
        "n1 = int(input(\"digite a nota da 1° trimestre :\"))\n",
        "\n",
        "n2 = int(input('Digite a nota do 2° trimestre :'))\n",
        "\n",
        "n3 = int(input('Digite a nota do 3° trimestre :'))\n",
        "\n",
        "n4 = int(input('Digite a nota do 4° trimestre :'))\n",
        "\n",
        "print('A sua media é', ((n1 + n2 + n3 + n4) / 4 ), '.')"
      ],
      "execution_count": 97,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "digite a nota da 1° trimestre :\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "error",
          "ename": "ValueError",
          "evalue": "ignored",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
            "\u001b[0;32m<ipython-input-97-d0c44975b99a>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# at4\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0mn1\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minput\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"digite a nota da 1° trimestre :\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mn2\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minput\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'Digite a nota do 2° trimestre :'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mValueError\u001b[0m: invalid literal for int() with base 10: ''"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "dohu1sl3M2QD",
        "outputId": "345d0d9b-5939-4976-cf73-bcb8fb02b3ea"
      },
      "source": [
        "# at5\n",
        "\n",
        "Metros = int(input('digite o valor em metros : '))\n",
        "\n",
        "Cm = 100\n",
        "\n",
        "print('O valor em cm é :', Metros * Cm , '.')"
      ],
      "execution_count": 50,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "digite o valor em metros : 5\n",
            "O valor em cm é : 500 .\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "xrcUmZQ6TXvG",
        "outputId": "95f4b9a7-c8bb-4b01-a474-1cd29bdca911"
      },
      "source": [
        "# at6 \n",
        "\n",
        "Area = int(input('Digite o raio do circulo :'))\n",
        "\n",
        "print('A raio do circulo é :', Area * 6.24 , '.')"
      ],
      "execution_count": 62,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Digite o raio do circulo :5\n",
            "A raio do circulo é : 31.200000000000003 .\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "SUTCCgMAc3Bb",
        "outputId": "c65f9ecd-b638-49ac-ded9-974802869afb"
      },
      "source": [
        "# at7\n",
        "\n",
        "Area = int(input('Isira o valor de um dos lados do quadrado :'))\n",
        "\n",
        "print('O dobro da area do quadrado é :', Area * 8 , '.')"
      ],
      "execution_count": 68,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Isira o valor de um dos lados do quadrado :8\n",
            "O dobro da area do quadrado é : 64 .\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "9mftHYXCeFP3",
        "outputId": "ed9ad06a-4e93-4393-cf3a-341728fb788a"
      },
      "source": [
        "# at8\n",
        "\n",
        "Hr = int(input('Quanto você ganha por hora trabalhada ?'))\n",
        "\n",
        "Mes = int(input('Quantas horas você trabalha no mês?'))\n",
        "\n",
        "print('Você ganha por mês :', Hr * Mes , '.')"
      ],
      "execution_count": 87,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Quanto você ganha por hora trabalhada ?5\n",
            "Quantas horas você trabalha no mês?50\n",
            "Você ganha por mês : 250 .\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "-c9bg1uEgOQi",
        "outputId": "8db79dd7-edf8-44ad-8411-3a5ff076aae3"
      },
      "source": [
        "# at9\n",
        "\n",
        "Number = float(input('Digite um numero :'))\n",
        "if Number > 0:\n",
        "   print('Este número é positivo')\n",
        "elif N == 0:\n",
        "   print('Este número é neutro')\n",
        "else:\n",
        "  print('Este número é negativo')"
      ],
      "execution_count": 74,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Digite um numero :5\n",
            "Este número é positivo\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "mLHh7t9viLmZ",
        "outputId": "200d9dee-ab50-4de9-a6f8-5878b5124375"
      },
      "source": [
        "# at10\n",
        "\n",
        "Number = input('Digite F ou M :')\n",
        "if Number == 'f':\n",
        "  print('Esta letra é f-feminina')\n",
        "elif Number == 'm':\n",
        " print('Esta letra é m-masculino')\n",
        "else:\n",
        "  print('Sexo inválido')"
      ],
      "execution_count": 90,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Digite F ou M :g\n",
            "Sexo inválido\n"
          ],
          "name": "stdout"
        }
      ]
    }
  ]
}

#10. Faça um CÓDIGO que verifique se uma letra digitada é "F" ou "M". Conforme a letra escrever: F - Feminino, M - Masculino, Sexo Inválido.
 
sexo = str (input ('Digite F ou M para saber o sexo. ') )
if sexo == 'F':
  print('Sexo feminino.')
elif sexo == 'M':
  print('Sexo masculino.')
else:
  print('Sexo inválido.')

n= float(input("Escolha um número:"))
print("O número informado foi {}".format(n))

n1= float(input("Escolha sua nota 1 :"))
n2= float(input("Escolha sua nota 2 :"))
n3= float(input("Escolha sua nota 3 :"))
n4= float(input("Escolha sua nota 4 :"))
nr= (n1+n2+n3+n4)/4
print("A média das 4 notas resulta em {}".format (nr))

n1= float(input("Escolha um número:"))
n2= float(input("Escolha um número:"))
print("A soma entre {0} e {1} resulta em {2}".format (n1, n2,(n1+n2)))